version: '3.8'

services:

  reverse-proxy:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
      - frontend

  frontend:
    build: ./material-applications/example-frontend
    ports:
      - 5000:5000
    container_name: frontend

  backend:
    build: ./material-applications/example-backend
    ports:
      - 8080:8080
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=postgres
      - POSTGRES_PASSWORD=example
      - REQUEST_ORIGIN=http://localhost
    container_name: backend
  
  redis:
    image: redis:latest
    ports:
      - 6379:6379

  postgres:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=example
    volumes:
      - ./database:/var/lib/postgresql/data
    container_name: postgres