version: '3.8'

services:

  reverse-proxy:
    image: nginx:latest
    networks:
      - proxy-network
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
      - frontend

  frontend:
    build: ./material-applications/example-frontend
    networks:
      - proxy-network
    environment:
      - REACT_APP_BACKEND_URL=http://localhost/api
    container_name: frontend

  backend:
    build: ./material-applications/example-backend
    networks:
      - proxy-network
      - db-network
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=postgres
      - POSTGRES_PASSWORD=example
      - REQUEST_ORIGIN=http://localhost
    container_name: backend
  
  redis:
    image: redis:latest
    networks:
      - db-network

  postgres:
    image: postgres:15-alpine
    restart: unless-stopped
    networks:
      - db-network
    environment:
      - POSTGRES_PASSWORD=example
    volumes:
      - ./database:/var/lib/postgresql/data
    container_name: postgres

networks:
  db-network:
  proxy-network:

volumes:
  postgres:
  nginx: